apply plugin: 'com.android.application'

android {
    signingConfigs {
        config {
            keyAlias 'KeyObninskRoutes'
            keyPassword 'asfgjk32rus'
            storeFile file('D:/Android/keystore/keystore.jks')
            storePassword 'asfgjk32rus'
        }
    }
    compileSdkVersion 22
    buildToolsVersion '22.0.1'
    defaultConfig {
        applicationId "ru.example.druger.obninskroutes"
        minSdkVersion 11
        targetSdkVersion 21
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.config
        }
        debug {
            signingConfig signingConfigs.config
        }
    }
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile 'com.android.support:appcompat-v7:22.2.0'
    compile 'com.android.support:support-v4:22.2.0'
    compile 'com.google.android.gms:play-services:7.5.0'
    compile 'com.readystatesoftware.sqliteasset:sqliteassethelper:2.0.1'
    compile files('libs/gson-2.3.1.jar')
    compile files('libs/gson-2.3.1-sources.jar')
    compile files('libs/gson-2.3.1-javadoc.jar')
}
